---

.script-git-submodule: &script-git-submodule
  - |
    git submodule sync --recursive
    git submodule update --init --recursive

.script-bootstrap-python: &script-bootstrap-python
  - |
    if ! [[ -x "$(command -v pipx)" ]]; then
      export DEBIAN_FRONTEND="noninteractive"
      echo "deb http://download.opensuse.org/repositories/home:/alvistack/xUbuntu_20.04/ /" | sudo tee /etc/apt/sources.list.d/home:alvistack.list
      curl -fsSL https://download.opensuse.org/repositories/home:alvistack/xUbuntu_20.04/Release.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/home_alvistack.gpg > /dev/null
      sudo -E apt-get update
      sudo -E apt-get install -y bzip2 ca-certificates curl flake8 gcc gnupg gzip iproute2 procps python3 python3-apt python3-cryptography python3-flake8 python3-jmespath python3-lxml python3-netaddr python3-pip python3-pipx python3-setuptools python3-venv python3-virtualenv python3-wheel python3-yamllint sudo tar unzip xz-utils zip
    fi
    sh -x -c "python3 --version"
    sh -x -c "pipx --version"
    sh -x -c "flake8 --version"
    sh -x -c "yamllint --version"

.script-bootstrap-ansible: &script-bootstrap-ansible
  - |
    if ! [[ -x "$(command -v ansible)" ]]; then
      export DEBIAN_FRONTEND="noninteractive"
      echo "deb http://download.opensuse.org/repositories/home:/alvistack/xUbuntu_20.04/ /" | sudo tee /etc/apt/sources.list.d/home:alvistack.list
      curl -fsSL https://download.opensuse.org/repositories/home:alvistack/xUbuntu_20.04/Release.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/home_alvistack.gpg > /dev/null
      sudo -E apt-get update
      sudo -E apt-get install -y ansible python3-ansible-lint python3-docker python3-netaddr python3-vagrant
    fi
    sh -x -c "ansible --version"
    sh -x -c "ansible-lint --version"

.script-bootstrap-libvirt: &script-bootstrap-libvirt
  - |
    if ! [[ -x "$(command -v qemu-system-x86_64)" ]]; then
      export DEBIAN_FRONTEND="noninteractive"
      echo "deb http://ppa.launchpad.net/savoury1/virtualisation/ubuntu focal main" | sudo tee /etc/apt/sources.list.d/savoury1.list
      curl -fsSL "http://keyserver.ubuntu.com/pks/lookup?op=get&search=0xE996735927E427A733BB653E374C7797FB006459" | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/savoury1.gpg > /dev/null
      sudo -E apt-get update
      sudo -E apt-get install -y binutils bridge-utils dnsmasq-base ebtables gcc libarchive-tools libguestfs-tools libvirt-clients libvirt-daemon-system libvirt-dev make qemu-system qemu-utils ruby-dev virt-manager
    fi
    sudo systemctl start libvirtd.service
    sh -x -c "sudo systemctl status --no-pager libvirtd.service"
    sh -x -c "qemu-system-x86_64 --version"
    sh -x -c "virsh --version"

.script-bootstrap-virtualbox: &script-bootstrap-virtualbox
  - |
    if ! [[ -x "$(command -v VBoxManage)" ]]; then
      export DEBIAN_FRONTEND="noninteractive"
      echo "deb [arch=amd64] https://download.virtualbox.org/virtualbox/debian focal contrib" | sudo tee /etc/apt/sources.list.d/virtualbox.list
      curl -fsSL https://www.virtualbox.org/download/oracle_vbox_2016.asc | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/virtualbox.gpg > /dev/null
      sudo -E apt-get update
      sudo -E apt-get install -y virtualbox-6.1
      export VERSION="$(VBoxManage --version | sed 's/^\([0-9]*\.[0-9]*\.[0-9]*\).*/\1/g')"
      curl -skL -O https://download.virtualbox.org/virtualbox/$VERSION/Oracle_VM_VirtualBox_Extension_Pack-$VERSION.vbox-extpack
      echo "y" | sudo VBoxManage extpack install Oracle_VM_VirtualBox_Extension_Pack-$VERSION.vbox-extpack --replace
      rm -rf Oracle_VM_VirtualBox_Extension_Pack-$VERSION.vbox-extpack
    fi
    sudo systemctl start vboxdrv.service
    sh -x -c "sudo systemctl status --no-pager vboxdrv.service"
    sh -x -c "VBoxManage --version"

.script-bootstrap-vagrant: &script-bootstrap-vagrant
  - |
    if ! [[ -x "$(command -v vagrant)" ]]; then
      export DEBIAN_FRONTEND="noninteractive"
      echo "deb [arch=amd64] https://apt.releases.hashicorp.com focal main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
      curl -fsSL https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/hashicorp.gpg > /dev/null
      sudo -E apt-get update
      sudo -E apt-get install -y vagrant
      vagrant plugin install vagrant-libvirt
    fi
    sh -x -c "vagrant --version"
    sh -x -c "vagrant plugin list"

.script-bootstrap-packer: &script-bootstrap-packer
  - |
    if ! [[ -x "$(command -v packer)" ]]; then
      export DEBIAN_FRONTEND="noninteractive"
      echo "deb [arch=amd64] https://apt.releases.hashicorp.com focal main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
      curl -fsSL https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/hashicorp.gpg > /dev/null
      sudo -E apt-get update
      sudo -E apt-get install -y packer
    fi
    sh -x -c "packer --version"

.script-linters: &script-linters
  - |
    yamllint .
    ansible-lint
    flake8

.script-packer-build: &script-packer-build
  - |
    sudo -E vagrant cloud auth login --token $VAGRANT_CLOUD_TOKEN
    cd $CI_PROJECT_DIR/packer/$_PACKER_BUILDER_PROVIDER-$_PACKER_BUILDER_VERSION
    sudo -E packer build packer.json

.script-vagrant-cloud-provider-upload: &script-vagrant-cloud-provider-upload
  - |
    if [[ -n "$CI_COMMIT_TAG" ]] && [[ "$CI_COMMIT_TAG" =~ ^[0-9]+\.[0-9]+\.[0-9]+ ]]; then
      export _VERSION="$CI_COMMIT_TAG"
    elif [[ -n "$CI_COMMIT_BRANCH" ]] && [[ "$CI_COMMIT_BRANCH" =~ master ]]; then
      export _VERSION="$(date +%Y%m%d).0.0"
    else
      exit 0
    fi
    sudo -E vagrant cloud auth login --token $VAGRANT_CLOUD_TOKEN
    cd $CI_PROJECT_DIR/packer/$_PACKER_BUILDER_PROVIDER-$_PACKER_BUILDER_VERSION
    export _ORG="$CI_PROJECT_NAMESPACE"
    export _BOX="$(echo $CI_PROJECT_NAME | sed "s/^vagrant-//g")-$_PACKER_BUILDER_VERSION"
    export _PROVIDER="$_PACKER_BUILDER_PROVIDER"
    export _CHECKSUM="$(sha256sum output-vagrant/package.box | awk '{ print $1 }')"
    curl -skL \
      --header "Content-Type: application/json" \
      --header "Authorization: Bearer $VAGRANT_CLOUD_TOKEN" \
      --data "{ \"box\": { \"username\": \"$_ORG\", \"name\": \"$_BOX\", \"is_private\": false } }" \
      https://app.vagrantup.com/api/v1/boxes | jq .
    curl -skL \
      --header "Content-Type: application/json" \
      --header "Authorization: Bearer $VAGRANT_CLOUD_TOKEN" \
      --data "{ \"version\": { \"version\": \"$_VERSION\" } }" \
      https://app.vagrantup.com/api/v1/box/$_ORG/$_BOX/versions | jq .
    curl -skL \
      --request DELETE \
      --header "Content-Type: application/json" \
      --header "Authorization: Bearer $VAGRANT_CLOUD_TOKEN" \
      https://app.vagrantup.com/api/v1/box/$_ORG/$_BOX/version/$_VERSION/provider/$_PROVIDER | jq .
    curl -skL \
      --header "Content-Type: application/json" \
      --header "Authorization: Bearer $VAGRANT_CLOUD_TOKEN" \
      --data "{ \"provider\": { \"name\": \"$_PROVIDER\", \"checksum_type\": \"sha256\", \"checksum\": \"$_CHECKSUM\" } }" \
      https://app.vagrantup.com/api/v1/box/$_ORG/$_BOX/version/$_VERSION/providers | jq .
    _UPLOAD_PATH=$(curl -skL \
      --header "Authorization: Bearer $VAGRANT_CLOUD_TOKEN" \
      https://app.vagrantup.com/api/v1/box/$_ORG/$_BOX/version/$_VERSION/provider/$_PROVIDER/upload | jq -r .upload_path)
    curl -skL \
      --request PUT \
      --header "Connection: keep-alive" \
      --upload-file output-vagrant/package.box \
      $_UPLOAD_PATH | jq .
    curl -skL \
      --request PUT \
      --header "Authorization: Bearer $VAGRANT_CLOUD_TOKEN" \
      https://app.vagrantup.com/api/v1/box/$_ORG/$_BOX/version/$_VERSION/release | jq .

.job-packer-build: &job-packer-build
  script:
    - *script-bootstrap-python
    - *script-bootstrap-ansible
    - *script-bootstrap-libvirt
    - *script-bootstrap-virtualbox
    - *script-bootstrap-vagrant
    - *script-bootstrap-packer
    - *script-linters
    - *script-packer-build

.job-vagrant-cloud-provider-upload: &job-vagrant-cloud-provider-upload
  script:
    - *script-bootstrap-vagrant
    - *script-vagrant-cloud-provider-upload

default:
  retry: 2
  before_script:
    - *script-git-submodule

build:libvirt-1.23:
  <<: *job-packer-build
  stage: build
  cache:
    key: "$CI_PIPELINE_ID-libvirt-1.23"
    paths:
      - packer/*/output-vagrant
  variables:
    _PACKER_BUILDER_PROVIDER: "libvirt"
    _PACKER_BUILDER_VERSION: "1.23"

deploy:libvirt-1.23:
  <<: *job-vagrant-cloud-provider-upload
  stage: deploy
  cache:
    key: "$CI_PIPELINE_ID-libvirt-1.23"
    paths:
      - packer/*/output-vagrant
    policy: pull
  variables:
    _PACKER_BUILDER_PROVIDER: "libvirt"
    _PACKER_BUILDER_VERSION: "1.23"
  needs:
    - build:libvirt-1.23

build:libvirt-1.22:
  <<: *job-packer-build
  stage: build
  cache:
    key: "$CI_PIPELINE_ID-libvirt-1.22"
    paths:
      - packer/*/output-vagrant
  variables:
    _PACKER_BUILDER_PROVIDER: "libvirt"
    _PACKER_BUILDER_VERSION: "1.22"

deploy:libvirt-1.22:
  <<: *job-vagrant-cloud-provider-upload
  stage: deploy
  cache:
    key: "$CI_PIPELINE_ID-libvirt-1.22"
    paths:
      - packer/*/output-vagrant
    policy: pull
  variables:
    _PACKER_BUILDER_PROVIDER: "libvirt"
    _PACKER_BUILDER_VERSION: "1.22"
  needs:
    - build:libvirt-1.22

build:libvirt-1.21:
  <<: *job-packer-build
  stage: build
  cache:
    key: "$CI_PIPELINE_ID-libvirt-1.21"
    paths:
      - packer/*/output-vagrant
  variables:
    _PACKER_BUILDER_PROVIDER: "libvirt"
    _PACKER_BUILDER_VERSION: "1.21"

deploy:libvirt-1.21:
  <<: *job-vagrant-cloud-provider-upload
  stage: deploy
  cache:
    key: "$CI_PIPELINE_ID-libvirt-1.21"
    paths:
      - packer/*/output-vagrant
    policy: pull
  variables:
    _PACKER_BUILDER_PROVIDER: "libvirt"
    _PACKER_BUILDER_VERSION: "1.21"
  needs:
    - build:libvirt-1.21

test:virtualbox-1.23:
  <<: *job-packer-build
  stage: test
  cache:
    key: "$CI_PIPELINE_ID-virtualbox-1.23"
    paths:
      - packer/*/output-vagrant
  variables:
    _PACKER_BUILDER_PROVIDER: "virtualbox"
    _PACKER_BUILDER_VERSION: "1.23"

deploy:virtualbox-1.23:
  <<: *job-vagrant-cloud-provider-upload
  stage: deploy
  cache:
    key: "$CI_PIPELINE_ID-virtualbox-1.23"
    paths:
      - packer/*/output-vagrant
    policy: pull
  variables:
    _PACKER_BUILDER_PROVIDER: "virtualbox"
    _PACKER_BUILDER_VERSION: "1.23"
  needs:
    - test:virtualbox-1.23

test:virtualbox-1.22:
  <<: *job-packer-build
  stage: test
  cache:
    key: "$CI_PIPELINE_ID-virtualbox-1.22"
    paths:
      - packer/*/output-vagrant
  variables:
    _PACKER_BUILDER_PROVIDER: "virtualbox"
    _PACKER_BUILDER_VERSION: "1.22"

deploy:virtualbox-1.22:
  <<: *job-vagrant-cloud-provider-upload
  stage: deploy
  cache:
    key: "$CI_PIPELINE_ID-virtualbox-1.22"
    paths:
      - packer/*/output-vagrant
    policy: pull
  variables:
    _PACKER_BUILDER_PROVIDER: "virtualbox"
    _PACKER_BUILDER_VERSION: "1.22"
  needs:
    - test:virtualbox-1.22

test:virtualbox-1.21:
  <<: *job-packer-build
  stage: test
  cache:
    key: "$CI_PIPELINE_ID-virtualbox-1.21"
    paths:
      - packer/*/output-vagrant
  variables:
    _PACKER_BUILDER_PROVIDER: "virtualbox"
    _PACKER_BUILDER_VERSION: "1.21"

deploy:virtualbox-1.21:
  <<: *job-vagrant-cloud-provider-upload
  stage: deploy
  cache:
    key: "$CI_PIPELINE_ID-virtualbox-1.21"
    paths:
      - packer/*/output-vagrant
    policy: pull
  variables:
    _PACKER_BUILDER_PROVIDER: "virtualbox"
    _PACKER_BUILDER_VERSION: "1.21"
  needs:
    - test:virtualbox-1.21
