---

# Copyright 2026 Wong Hoi Sing Edison <hswong3i@pantarei-design.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

_rpm_key:
  - key: https://downloadcontent.opensuse.org/tumbleweed/repo/oss/gpg-pubkey-29b700a4-62b07e22.asc
    fingerprint: AD485664E901B867051AB15F35A2F86E29B700A4
    state: present

_yum_repository:
  - file: repo-debug
    name: repo-debug
    description: openSUSE-Tumbleweed-Debug
    baseurl: http://downloadcontent.opensuse.org/debug/tumbleweed/repo/oss
    enabled: false
    priority: "2"
    module_hotfixes: true
    gpgcheck: true
    gpgkey: http://downloadcontent.opensuse.org/debug/tumbleweed/repo/oss/repodata/repomd.xml.key
    state: present
  - file: repo-non-oss
    name: repo-non-oss
    description: openSUSE-Tumbleweed-Non-Oss
    baseurl: http://downloadcontent.opensuse.org/tumbleweed/repo/non-oss
    enabled: true
    priority: "2"
    module_hotfixes: true
    gpgcheck: true
    gpgkey: http://downloadcontent.opensuse.org/tumbleweed/repo/non-oss/repodata/repomd.xml.key
    state: present
  - file: repo-openh264
    name: repo-openh264
    description: Open H.264 Codec (openSUSE Tumbleweed)
    baseurl: http://codecs.opensuse.org/openh264/openSUSE_Tumbleweed
    enabled: true
    priority: "2"
    module_hotfixes: true
    gpgcheck: true
    gpgkey: http://codecs.opensuse.org/openh264/openSUSE_Tumbleweed/repodata/repomd.xml.key
    state: present
  - file: repo-oss
    name: repo-oss
    description: openSUSE-Tumbleweed-Oss
    baseurl: http://downloadcontent.opensuse.org/tumbleweed/repo/oss
    enabled: true
    priority: "2"
    module_hotfixes: true
    gpgcheck: true
    gpgkey: http://downloadcontent.opensuse.org/tumbleweed/repo/oss/repodata/repomd.xml.key
    state: present
  - file: repo-source
    name: repo-source
    description: openSUSE-Tumbleweed-Source
    baseurl: http://downloadcontent.opensuse.org/source/tumbleweed/repo/oss
    enabled: false
    priority: "2"
    module_hotfixes: true
    gpgcheck: true
    gpgkey: http://downloadcontent.opensuse.org/source/tumbleweed/repo/oss/repodata/repomd.xml.key
    state: present
  - file: repo-update
    name: repo-update
    description: openSUSE-Tumbleweed-Update
    baseurl: http://downloadcontent.opensuse.org/update/tumbleweed
    enabled: true
    priority: "2"
    module_hotfixes: true
    gpgcheck: true
    gpgkey: http://downloadcontent.opensuse.org/update/tumbleweed/repodata/repomd.xml.key
    state: present

_zypper:
  - { state: latest, name: ca-certificates }
  - { state: latest, name: cloud-init }
  - { state: latest, name: curl }
  - { state: latest, name: gcc }
  - { state: latest, name: growpart }
  - { state: latest, name: iproute2 }
  - { state: latest, name: kernel-default }
  - { state: latest, name: kernel-default-devel }
  - { state: latest, name: libXmu6 }
  - { state: latest, name: libXt6 }
  - { state: latest, name: make }
  - { state: latest, name: openssh }
  - { state: latest, name: perl }
  - { state: latest, name: python3 }
  - { state: latest, name: rsync }
  - { state: latest, name: shadow }
  - { state: latest, name: sudo }
  - { state: latest, name: util-linux }
