---

# (c) Wong Hoi Sing Edison <hswong3i@pantarei-design.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# etcd
etcd_trusted_ca_file: "/etc/etcd/pki/ca.crt"

# kube_master
kubernetes_cluster_name: "{{ hostvars[groups['kube_master'][0]].ansible_machine_id | to_uuid }}"
kubernetes_etcd:
  external:
    endpoints: >-
      {%- set _ns = namespace() -%}
      {%- set _ns._params = [] -%}
      {%- for host in groups['etcd'] -%}
      {%-   set _ns._params = _ns._params + ["https://" + hostvars[host].ansible_default_ipv4.address + ":2379"] -%}
      {%- endfor -%}
      {{ _ns._params }}
    caFile: "/etc/kubernetes/pki/etcd/ca.crt"
    certFile: "/etc/kubernetes/pki/apiserver-etcd-client.crt"
    keyFile: "/etc/kubernetes/pki/apiserver-etcd-client.key"
kube_apiserver_bind_port: "6443"
kube_apiserver_endpoint: "{{ hostvars[groups['kube_master'][0]].ansible_default_ipv4.address }}:{{ kube_apiserver_bind_port }}"
kube_apiserver_csr_common_name: "{{ groups['kube_master'][0] }}"
kube_apiserver_csr_subject_alt_name: >-
  {%- set _ns = namespace() -%}
  {%- set _ns._params = ["DNS:localhost", "IP:127.0.0.1"] -%}
  {%- for host in groups['kube_master'] -%}
  {%-   set _ns._params = _ns._params + ["DNS:" + host, "IP:" + hostvars[host].ansible_default_ipv4.address] -%}
  {%- endfor -%}
  {{ _ns._params }}
