---

# (c) Wong Hoi Sing Edison <hswong3i@pantarei-design.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: vagrant destroy
      vagrant:
        instance_name: "{{ item.name }}"
        platform_box: "{{ item.box | default(omit) }}"
        provider_name: "{{ molecule_yml.driver.provider.name }}"
        provider_options: "{{ item.provider_options | default(omit) }}"
        provider_raw_config_args: "{{ item.provider_raw_config_args | default(omit) }}"
        force_stop: "{{ item.force_stop | default(true) }}"
        state: "destroy"
      loop_control:
        label: "{{ item.name }}"
      loop: "{{ molecule_yml.platforms }}"
      register: result
