---

# Copyright 2024 Wong Hoi Sing Edison <hswong3i@pantarei-design.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: converge | all
  hosts: all
  remote_user: root
  become: true
  tasks:
    - name: include default variables
      ansible.builtin.include_vars: "./vars/main.yml"

    - name: include release specific variables
      ansible.builtin.include_vars: "{{ _loop_var }}"
      loop: "{{ query('first_found', _params) }}"
      loop_control:
        loop_var: _loop_var
      vars:
        _params:
          files:
            - "{{ ansible_distribution | lower }}-{{ ansible_distribution_version | lower }}.yml"
            - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
            - "{{ ansible_distribution | lower }}.yml"
            - "{{ ansible_os_family | lower }}-{{ ansible_distribution_version | lower }}.yml"
            - "{{ ansible_os_family | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
            - "{{ ansible_os_family | lower }}.yml"
          paths:
            - "./vars"
          skip: true

    - name: include release specific tasks
      ansible.builtin.include_tasks: "{{ _loop_var }}"
      loop: "{{ query('first_found', _params) }}"
      loop_control:
        loop_var: _loop_var
      vars:
        _params:
          files:
            - "{{ ansible_distribution | lower }}-{{ ansible_distribution_version | lower }}.yml"
            - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
            - "{{ ansible_distribution | lower }}.yml"
            - "{{ ansible_os_family | lower }}-{{ ansible_distribution_version | lower }}.yml"
            - "{{ ansible_os_family | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
            - "{{ ansible_os_family | lower }}.yml"
          paths:
            - "./tasks"
          skip: true

    - name: include default tasks
      ansible.builtin.include_tasks: "./tasks/main.yml"

    - name: include role
      ansible.builtin.include_role:
        name: python

    - name: include role
      ansible.builtin.include_role:
        name: ansible

    - name: include role
      ansible.builtin.include_role:
        name: locales

    - name: include role
      ansible.builtin.include_role:
        name: timezone

    - name: include role
      ansible.builtin.include_role:
        name: kernel

    - name: include role
      ansible.builtin.include_role:
        name: cloud_init

    - name: include role
      ansible.builtin.include_role:
        name: sshd

    - name: include role
      ansible.builtin.include_role:
        name: crun

    - name: include role
      ansible.builtin.include_role:
        name: containers_common

    - name: include role
      ansible.builtin.include_role:
        name: containernetworking_plugins

    - name: include role
      ansible.builtin.include_role:
        name: conmon

    - name: include role
      ansible.builtin.include_role:
        name: skopeo

    - name: include role
      ansible.builtin.include_role:
        name: buildah

    - name: include role
      ansible.builtin.include_role:
        name: podman

- name: converge | kube_master:kube_node
  hosts: kube_master:kube_node
  remote_user: root
  become: true
  tasks:
    - name: include role
      ansible.builtin.include_role:
        name: cri_o

    - name: include role
      ansible.builtin.include_role:
        name: cri_tools

    - name: include role
      ansible.builtin.include_role:
        name: kube_kubectl

    - name: include role
      ansible.builtin.include_role:
        name: kube_kubelet

    - name: include role
      ansible.builtin.include_role:
        name: kube_kubeadm

- name: converge | etcd
  hosts: etcd
  remote_user: root
  become: true
  tasks:
    - name: include role
      ansible.builtin.include_role:
        name: etcd

- name: converge | kube_master
  hosts: kube_master
  remote_user: root
  become: true
  tasks:
    - name: include role
      ansible.builtin.include_role:
        name: kube_master

- name: converge | kube_node
  hosts: kube_node:!kube_master
  remote_user: root
  become: true
  tasks:
    - name: include role
      ansible.builtin.include_role:
        name: kube_node

- name: converge | ansible
  hosts: ansible
  remote_user: root
  become: true
  tasks:
    - name: include role
      ansible.builtin.include_role:
        name: sonobuoy
